### ISSUE TITLE
请求将个推SDK版本更新为最新版本

### ISSUE THREAD

**Issue by money150604** [candyan/GexinSDK#1]
请求将个推SDK版本更新为最新版本

**Comment by candyan** [comment]
@money150604 1.1.1 is already in cocoapods

ps: 从我的使用上来看。个推极其不靠谱，推荐用极光 or  leancloud or amazon sns. 如果就是个demo 那就无所谓了。。╮(╯_╰)╭

**Comment by money150604** [comment]
我这边Android使用了 个推  感觉还挺好   后台不轻易换，我也只能在IOS里面使用这个了

**Comment by money150604** [comment]
iOS SDK下载（iOS SDK 1.2.0 发布时间：2015-7-2）

**Comment by candyan** [comment]
@money150604  1.2.0 已经添加上了。。。
