### ISSUE TITLE
个推官方已更新1.4.1期望更新一下

### ISSUE THREAD

**Issue by fmricky** [candyan/GexinSDK#10]
个推官方已更新1.4.1期望更新一下
http://docs.getui.com/pages/viewpage.action?pageId=590248

**Comment by fmricky** [comment]
已发起PR #11 
第一次对Pods库进行PR，麻烦多检查确认后再合并

**Comment by candyan** [comment]
@fmricky 已经提交到 cocoapods 上了。。
