### ISSUE TITLE
更新后编译出错

### ISSUE THREAD

**Issue by money150604** [candyan/GexinSDK#2]
Undefined symbols for architecture armv7:
  "_AVAudioSessionCategoryPlayback", referenced from:
      -[GXBackgroundClient playMedia] in libGeTuiSdk-1.2.0.a(GXBackgroundClient.o)
  "_OBJC_CLASS_$_AVAudioPlayer", referenced from:
      objc-class-ref in libGeTuiSdk-1.2.0.a(GXBackgroundClient.o)
  "_OBJC_CLASS_$_AVAudioSession", referenced from:
      objc-class-ref in libGeTuiSdk-1.2.0.a(GXBackgroundClient.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
是否加少了依赖包

**Comment by candyan** [comment]
加个 AVFoundation 试下... 如果OK了。。我加到 pod 依赖里面

**Comment by money150604** [comment]
OK   加了编译通过   是否能在  podspec 文件加上

**Comment by candyan** [comment]
OK

**Comment by money150604** [comment]
thx

**Comment by candyan** [comment]
1.2.0.1 version @money150604
