### ISSUE TITLE
你好，期望更新到1.2.1

### ISSUE THREAD

**Issue by iOnRoad** [candyan/GexinSDK#5]
1.2.0版本现在有bug。期待你更新到1.2.1版本。谢谢你的贡献。

**Comment by candyan** [comment]
改成 GetuiSDK 了。。。。更新了下 readme 你可以看下。。。

https://github.com/candyan/GexinSDK @iOnRoad

**Comment by iOnRoad** [comment]
亲，Pod库里还搜索不到getui的相关。是还没审核过吗？：）

**Comment by candyan** [comment]
@iOnRoad `pod repo update` 一下吧 你用的是master吧 还是某个国内镜像？

**Comment by candyan** [comment]
done
